# Image Representation

In [1]:
import cv2
img = cv2.imread('LM10.jpg',1) #extracts the pixels from the image and load into a numpy array
print(img)  

[[[78 45 25]
  [79 46 26]
  [79 46 26]
  ...
  [69 66 58]
  [69 66 58]
  [70 67 59]]

 [[78 45 25]
  [79 46 26]
  [79 46 26]
  ...
  [69 66 58]
  [69 66 58]
  [70 67 59]]

 [[80 45 25]
  [81 46 26]
  [81 46 26]
  ...
  [68 65 57]
  [69 66 58]
  [69 66 58]]

 ...

 [[28 21 12]
  [24 17  8]
  [18 12  5]
  ...
  [23 21 13]
  [23 21 13]
  [23 21 13]]

 [[24 17  8]
  [21 14  5]
  [15  9  2]
  ...
  [20 18 10]
  [21 19 11]
  [22 20 12]]

 [[22 15  6]
  [19 12  3]
  [13  7  0]
  ...
  [17 15  7]
  [17 15  7]
  [19 17  9]]]


In [2]:
print(type(img))

<class 'numpy.ndarray'>


In [3]:
print(img.shape) #height==no. of rows,width==no.of columns,no. of channels RGB or BGR(channel means how many values representing each pixel)

(916, 735, 3)


# Understanding The Numpy Array

In [4]:
#lets take an 2*2 image i.e. 4 pixels
"""
[
    [  [5,3,6] ,   [8,3,4]       ]
    [  [255,0,9] , [128,216,167] ]
    
]

"""

#The above array has 2 rows and 2 columns and each element got represented by a list of 3 values(channels) , usually it is RGB but in case of cv2 it is BGR
#So the above array's shape is (2,2,3)
#[23,34,52] in cv2 respectively Blue Green Red ,[0,0,0]means black and [255,255,255] means white
# values in each position valid are 0-255 where 0=None and 255 = All
#So,[255,0,0] = Blue(All blue ,no green and no red) & [128,0,0] = Lighter Blue

'\n[\n    [  [5,3,6] ,   [8,3,4]       ]\n    [  [255,0,9] , [128,216,167] ]\n    \n]\n'

# Accessing Pixel Values

In [5]:
print(img[0][78:457])

[[  2   0   0]
 [  0   0   0]
 [  2   3   1]
 ...
 [101 119 148]
 [107 125 154]
 [116 134 163]]


In [6]:
print(img[0][456])

[116 134 163]


In [7]:
print(img[0 , 78:457])

[[  2   0   0]
 [  0   0   0]
 [  2   3   1]
 ...
 [101 119 148]
 [107 125 154]
 [116 134 163]]


In [8]:
print(img[0,456])

[116 134 163]


# Changing Pixel Colors

In [9]:
import random
for i in range(100):
    for j in range(img.shape[1]):
        img[i][j] = [random.randint(0,255),random.randint(0,255),random.randint(0,255)]

cv2.imshow('Image',img) # first parameter is the window name which will be popped up
cv2.waitKey(0)          # 0:waiting for infinite amount of time until we press any other key and any other value means it will wait for that many seconds till then if we dont press any key it will automatically get closed 
cv2.destroyAllWindows()

# Copying and Pasting Parts of Image

In [13]:
img = cv2.imread('LM10.jpg',1) 
tag = img[300:400,600:700]
img[200:300,400:500]=tag   #left side's shape i.e. the part of the image where copying is happening should be same size as the tag

cv2.imshow('Image',img) # first parameter is the window name which will be popped up
cv2.waitKey(0)          # 0:waiting for infinite amount of time until we press any other key and any other value means it will wait for that many seconds till then if we dont press any key it will automatically get closed 
cv2.destroyAllWindows()